# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 75%
        threshold: 1%
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/"
  - "scripts/"
  - "examples/"
  - "docs/"
  - "setup.py"
  - "**/conftest.py"
