name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when I try to... because..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "I would like Polyglot FFI to support..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: "I considered using... but..."

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Show how you'd like to use this feature
      render: python
      placeholder: |
        # Example of how I'd like to use this feature
        polyglot-ffi generate --new-feature

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - CLI / Commands
        - Code Generation
        - Type System
        - Error Handling
        - Documentation
        - Performance
        - Developer Experience
        - New Language Support
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a real-world scenario where this would be useful
      placeholder: "In my project, I need to..."

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute?
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to write documentation for this feature

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have checked the documentation
          required: true
