/* Generated by polyglot-ffi */
/* encryption_stubs.c */

#include <string.h>
#include <caml/mlvalues.h>
#include <caml/memory.h>
#include <caml/alloc.h>
#include <caml/callback.h>

/* Wrapper for OCaml encrypt function */
char* ml_encrypt(char* arg0) {
    CAMLparam0();
    CAMLlocal2(ml_arg0, ml_result);

    ml_arg0 = caml_copy_string(arg0);
    ml_result = caml_callback(*caml_named_value("encrypt"), ml_arg0);

    char* result = strdup(String_val(ml_result));
    CAMLreturnT(char*, result);
}

/* Wrapper for OCaml decrypt function */
char* ml_decrypt(char* arg0) {
    CAMLparam0();
    CAMLlocal2(ml_arg0, ml_result);

    ml_arg0 = caml_copy_string(arg0);
    ml_result = caml_callback(*caml_named_value("decrypt"), ml_arg0);

    char* result = strdup(String_val(ml_result));
    CAMLreturnT(char*, result);
}

/* Wrapper for OCaml hash function */
char* ml_hash(char* arg0) {
    CAMLparam0();
    CAMLlocal2(ml_arg0, ml_result);

    ml_arg0 = caml_copy_string(arg0);
    ml_result = caml_callback(*caml_named_value("hash"), ml_arg0);

    char* result = strdup(String_val(ml_result));
    CAMLreturnT(char*, result);
}

/* Wrapper for OCaml validate function */
int ml_validate(char* arg0, char* arg1) {
    CAMLparam0();
    CAMLlocal3(ml_arg0, ml_arg1, ml_result);

    ml_arg0 = caml_copy_string(arg0);
    ml_arg1 = caml_copy_string(arg1);
    ml_result = caml_callback(*caml_named_value("validate"), ml_arg0, ml_arg1);

    int result = Bool_val(ml_result);
    CAMLreturnT(int, result);
}

