(* Generated by polyglot-ffi *)
open Ctypes

module Functions (F : Ctypes.FOREIGN) = struct
  let encrypt = 
    F.foreign "ml_encrypt"
      (string @-> returning string)

  let decrypt = 
    F.foreign "ml_decrypt"
      (string @-> returning string)

  let hash = 
    F.foreign "ml_hash"
      (string @-> returning string)

  let validate = 
    F.foreign "ml_validate"
      (string @-> string @-> returning bool)

end
