"""
Dune build system configuration generator.
"""

from polyglot_ffi.utils.naming import sanitize_module_name


class DuneGenerator:
    """Generate Dune build configuration files."""

    def generate_dune(self, module_name: str) -> str:
        """Generate dune file for the bindings library."""
        safe_name = sanitize_module_name(module_name)
        return f"""; Generated by polyglot-ffi
(library
 (name {safe_name}_bindings)
 (public_name {safe_name}_bindings)
 (libraries ctypes ctypes.foreign)
 (ctypes
  (external_library_name {safe_name})
  (build_flags_resolver
   (vendored (c_flags :standard) (c_library_flags :standard)))
  (headers (preamble "#include \\"{safe_name}_stubs.h\\""))
  (type_description
   (instance Type)
   (functor Type_description))
  (function_description
   (concurrency sequential)
   (instance Function)
   (functor Function_description))
  (generated_types Types_generated)
  (generated_entry_point C)))

; Compile C stubs to object file
(rule
 (targets {safe_name}_stubs.o)
 (deps {safe_name}_stubs.c {safe_name}_stubs.h)
 (action
  (run gcc -c -I%{{ocaml_where}} -fPIC {safe_name}_stubs.c -o {safe_name}_stubs.o)))

; Build OCaml object file for standalone shared library
(rule
 (targets lib{safe_name}_ocaml.o)
 (deps {safe_name}.ml {safe_name}.mli)
 (action
  (progn
   (run ocamlfind ocamlopt -c -thread -package ctypes.foreign {safe_name}.mli)
   (run ocamlfind ocamlopt -thread -output-obj -o lib{safe_name}_ocaml.o
    -package ctypes.foreign -linkpkg
    {safe_name}.ml))))

; Create .dylib from object files on macOS
(rule
 (targets lib{safe_name}.dylib)
 (deps lib{safe_name}_ocaml.o {safe_name}_stubs.o)
 (enabled_if (= %{{system}} macosx))
 (mode promote)
 (action
  (run gcc -dynamiclib -o lib{safe_name}.dylib
   lib{safe_name}_ocaml.o {safe_name}_stubs.o
   -L%{{ocaml_where}} -lasmrun -lunix -lthreadsnat)))

; Create .so from object files on Linux
(rule
 (targets lib{safe_name}.so)
 (deps lib{safe_name}_ocaml.o {safe_name}_stubs.o)
 (enabled_if (= %{{system}} linux))
 (mode promote)
 (action
  (run gcc -shared -o lib{safe_name}.so
   lib{safe_name}_ocaml.o {safe_name}_stubs.o
   -L%{{ocaml_where}} -lasmrun -lunix -lthreadsnat)))
"""

    def generate_dune_project(self, module_name: str) -> str:
        """Generate dune-project file."""
        safe_name = sanitize_module_name(module_name)
        return f"""(lang dune 3.16)
(using ctypes 0.3)

; Generated by polyglot-ffi

(name {safe_name}_bindings)

(generate_opam_files true)

(package
 (name {safe_name}_bindings)
 (synopsis "OCaml-Python bindings for {module_name}")
 (description "Auto-generated FFI bindings by polyglot-ffi")
 (depends
  (ocaml (>= 4.14))
  (dune (>= 3.16))
  (ctypes (>= 0.20.0))
  (ctypes-foreign (>= 0.20.0))))
"""
