name: Documentation

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  build-and-deploy:
    name: Build and deploy documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install mkdocs mkdocs-material mkdocstrings[python] mike

    - name: Build documentation
      run: |
        mkdocs build --strict

    - name: Test documentation links
      run: |
        # Install link checker
        pip install linkchecker || true
        # Check links (continue on error for now)
        linkchecker site/ || true

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        mkdocs gh-deploy --force

    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v5
      with:
        name: documentation-site
        path: site/
        retention-days: 7
